name: Atualizar Estatísticas do Perfil

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Gerar Card de Estatísticas
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=LLLucasLL&show_icons=true&include_all_commits=true&theme=tokyonight&locale=pt-br
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerar Card de Linguagens
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=LLLucasLL&layout=compact&langs_count=8&theme=tokyonight&locale=pt-br
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit e Push Manual das Alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add profile/stats.svg profile/top-langs.svg
          
          if git diff --staged --quiet; then
            echo "Nenhuma alteração nos cards para commitar."
          else
            git commit -m "Atualização automática dos cards de estatísticas [skip ci]"
            git pull --rebase origin main
            git push origin main
          fi
